name: Test on RISC-V

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Download GCC
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install gdown
        gdown https://drive.google.com/uc?id=1U3JaUqWyRYvlhfA3lVEfwu56em-Gwonl
        mkdir xuantie-gcc && cd xuantie-gcc
        tar -xf ../xuantie-gcc-v2.8.0.tar.gz

    - name: Build
      run: |
        export PATH=${{ github.workspace }}/xuantie-gcc/bin/:$PATH
        make run testcc VERBOSITY=1

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: llama2_riscv
        path: |
          ./run
          ./testc

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: llama2_riscv

      - name: Run tests
        run: |
          chmod +x ./testc
          ./testc
